### ISSUE TITLE
Basic question on adding new bower files

### ISSUE THREAD

**Issue by davidtlee** [mwaylabs/generator-m#142]
I installed generator-m and it seems to be working fine without modifications.

I started trying to add my own files / modifications. All I've done so far is:
1) Add dependencies to bower.json
2) Do `bower install`
3) Add those dependencies in `app/index.html`

Without doing anything else, I'm getting this error:

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Transform.onerror (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:95:17)
    at Transform.<anonymous> (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/index.js:79:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/index.js:67:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/index.js:45:36)
    at Array.forEach (native)
    at Transform._transform (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/index.js:42:15)
    at Transform._read (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/davidlee/Developer/synapp-cordova/node_modules/gulp-useref/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

Any idea what's going on?

**Comment by gruppjo** [comment]
Hi @davidtlee 
Sorry you ran into problems. Usually what you are trying to do should work without any further ado. 

Normally when adding new bower component though you don't need to manually add the resources to the `index.hml`, the injection is covered when you start your `gulp watch` task. 
The error you ran in seems to be hailing from gulp-useref. An error like this can occur if you specify a file in the `index.html` that doesn't exist (see https://github.com/jonkemp/gulp-useref/issues/44)
Can you please provide the lines in question you changed in your `bower.json` and `index.html`, so we can reproduce this error?

**Comment by gruppjo** [comment]
closing because we couldn't reproduce and because of inactivity
