### ISSUE TITLE
Missing gulp-if in generated application

### ISSUE THREAD

**Issue by arlaneenalra** [mwaylabs/generator-m#163]
I ran into a missing npm module after creating a project for the first time.

```
[08:37:01] Using gulpfile ~/code/android/js/generator-m/gulpfile.js
[08:37:01] Starting 'connect'...
[08:37:01] Finished 'connect' after 9.25 ms
[08:37:01] Starting 'styles'...
[08:37:02] Starting 'wiredep'...
[08:37:02] Starting 'bower-fonts'...
[08:37:02] Starting 'environment'...
[08:37:02] Starting 'jshint'...
[08:37:03] 'jshint' errored after 619 ms
[08:37:03] AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (/home/jules/code/android/js/generator-m/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.defineProperty.get (/home/jules/code/android/js/generator-m/node_modules/gulp-load-plugins/index.js:68:18)
    at Gulp.<anonymous> (/home/jules/code/android/js/generator-m/gulp_tasks/linting.js:20:17)
    at module.exports (/home/jules/code/android/js/generator-m/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/jules/code/android/js/generator-m/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/jules/code/android/js/generator-m/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /home/jules/code/android/js/generator-m/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/home/jules/code/android/js/generator-m/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
Started connect web server on http://localhost:9000
[08:37:03] gulp-inject 1 files into main/constants/config-const.js.
[08:37:03] Finished 'wiredep' after 1.63 s
[08:37:03] Finished 'environment' after 1.61 s
[08:37:04] Finished 'bower-fonts' after 1.7 s
[08:37:04] gulp-ruby-sass: directory main/styles
[08:37:08] gulp-ruby-sass: write main/styles/main.css
[08:37:08] Finished 'styles' after 7.65 s
```

With a little debugging I was able to trace down that the jshint needed gulp-if installed.  What would it take to get this added to the generated package.json?

**Comment by gruppjo** [comment]
Hi @arlaneenalra,

sorry you ran into troubles. This is odd... gulp-if is included per default in the `package.json` of the generated project. See https://github.com/mwaylabs/generator-m/blob/master/app/templates/_package.json#L16
From the looks of your output, you ran `gulp watch`, which is very well tested and shouldn't cause any problems.

Thus I'm suspecting that the problem lies with npm, or your local `npm_modules` folder.

1. Did you run `gulp watch` or any other command?
2. `npm install` ran without any errors, while setting up the project with the generator?
3. Were you able to somehow get rid of the error yourself?

Here's what you could try in the meantime

- delete the `node_modules` folder and run `npm install` again, see if that fixes the problem
- run `yo m --skip-prompts --no-cordova` and see if that produces the same error

Please report back with any findings!

**Comment by arlaneenalra** [comment]
Looking at this again, it does appear that the problem lies in my internet connection during the build.  'yo' reported all done but there were errors further back in the output for ```npm install```.  Beyond the fact that yo didn't report a problem this can probably be disregarded.

**Comment by kschio** [comment]
Hi there,

I encountered the error as well, clearing the npm cache and running the install command by "hand" helped.

Cheers.
