### ISSUE TITLE
fix issue with new generator version

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#166]
occurs with versions `>0.18.6`, when running yo m
```
/Users/jonathan/Projects/generator-m/node_modules/yeoman-generator/lib/base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (/Users/jonathan/Projects/generator-m/node_modules/yeoman-generator/lib/base.js:445:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:330:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:155:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by gruppjo** [comment]
update yo `npm install -g yo`. See: https://github.com/yeoman/generator/issues/762
