### ISSUE TITLE
update dev dependencies

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#167]
and fix this issue when gulp watch is triggered by file change
```
[11:18:31] Starting 'istanbul'...
[11:18:31] Plumber found unhandled error:
 RangeError in plugin 'gulp-mocha'
Message:
    Maximum call stack size exceeded
Stack:
    at handleException (/Users/jonathan/Projects/generator-m/node_modules/gulp-mocha/index.js:38:26)
    at /Users/jonathan/Projects/generator-m/node_modules/gulp-mocha/index.js:57:5
    at b (domain.js:183:18)
    at Domain.run (domain.js:123:23)
    at Stream.<anonymous> (/Users/jonathan/Projects/generator-m/node_modules/gulp-mocha/index.js:43:5)
    at _end (/Users/jonathan/Projects/generator-m/node_modules/gulp-mocha/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/jonathan/Projects/generator-m/node_modules/gulp-mocha/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/jonathan/Projects/generator-m/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
```

**Comment by gruppjo** [comment]
fixed https://github.com/mwaylabs/generator-m/commit/63a2b2a9be9dd35a93247ab0a48cfc04a91c31a1
