### ISSUE TITLE
check before build, if bower components are up to date (prevent error)

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#93]
- when not, stop the build

- right now the situation when having not all components installed from bower, you get this ugly error:
```events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Transform.onerror (/Users/mathiasmaier/Projects/TestProject/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:95:17)
    at Transform.<anonymous> (/Users/mathiasmaier/ProjectsTestProject/node_modules/gulp-useref/index.js:79:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mathiasmaier/Projects/TestProject/node_modules/gulp-useref/index.js:67:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mathiasmaier/Projects/TestProject/node_modules/gulp-useref/index.js:45:36)
    at Array.forEach (native)
```

**Comment by gruppjo** [comment]
this should be done with #115
